CREATE TABLE [dbo].[tRevisionLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EventType] [nvarchar](100) NULL,
	[ObjectType] [nvarchar](100) NULL,
	[DevRevision] [nvarchar](100) NULL
 CONSTRAINT [PK_tVersion] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
