CREATE TABLE [dbo].[tPayments](
	[ID] [int] IDENTITY(1,1) not null,
	[Summ] [numeric](10,2) NOT NULL
 CONSTRAINT [PK_tPayments] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]